// src/components/Navbar/navbar.svelte

<script>
// @ts-nocheck


</script>

<div class="topnav">
    <a class="active" href="#home">Home</a>
    <a href="#profile">Profile</a>
    <a href="#citation">Citation</a>
    <a href="#voicenote">Voice note</a>
    <a href="#testimonials">Testimonials</a>

  </div>
  
  <style>
    /* Add a black background color to the top navigation */
.topnav {

    overflow: hidden;
    width:100%;
    height: 100%;
    display: flex;
    justify-content: space-evenly;
    margin:10px;


}

/* Style the links inside the navigation bar */
.topnav a {
    float: left;
    color: #FFFF;
    line-height: 40px!important;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
    font-size: 17px;

}

/* Change the color of links on hover */
.topnav a:hover {
    text-decoration: underline 1.5px;
    text-decoration-style: wavy ;
    text-decoration-color: #affff6;
}

/* Add a color to the active/current link */
.topnav a.active {
    background-color: #00402E;


    color: #FFF;

}
  </style>

// motiv-action/src/components/Navbar/NavBar.tsx
import * as React from "react";

import SvgLogo from "../../assets/images/logo.svg";

const NavBar: React.FC = () => {
  return (
    <nav className="overflow-hidden	w-full h-full	flex justify-evenly m-10 ">
      {" "}
      <img className="w-20" src={SvgLogo} alt="logo" />
      <a
        className="float-lef text-red-400 text-center	leading-8 p-3.5 no-underline	text-base	hover:bg-yellow-600 active:bg-amber-400 active:text-black"
        href="#home"
      >
        Home
      </a>
      <a
        className="float-lef  text-center	leading-8 p-3.5 no-underline	text-base	hover:bg-yellow-600 active:bg-amber-400 "
        href="#profile"
      >
        Profile
      </a>
      <a
        className="float-lef  text-center	leading-8 p-3.5 no-underline	text-base	hover:bg-yellow-600 active:bg-amber-400 "
        href="#citation"
      >
        Citation
      </a>
      <a
        className="float-lef  text-center	leading-8 p-3.5 no-underline	text-base	hover:bg-yellow-600 active:bg-amber-400 "
        href="#voicenote"
      >
        Voice note
      </a>
      <a
        className="float-lef  text-center	leading-8 p-3.5 no-underline	text-base	hover:bg-yellow-600 active:bg-amber-400"
        href="#testimonials"
      >
        Testimonials
      </a>
    </nav>
  );
};

export default NavBar;
